version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: symfony/yaml
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/error-handler
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/options-resolver
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/flex
    versions:
    - 1.11.0
    - 1.12.0
    - 1.12.1
  - dependency-name: guzzlehttp/guzzle
    versions:
    - 7.2.0
  - dependency-name: predis/predis
    versions:
    - 1.1.6
  - dependency-name: symfony/deprecation-contracts
    versions:
    - 2.2.0
  - dependency-name: symfony/service-contracts
    versions:
    - 2.2.0
  - dependency-name: symfony/event-dispatcher-contracts
    versions:
    - 2.2.0
