version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-

      - run: composer self-update
      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
            - ./node_modules
            - /tmp/phpredis
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run: ./vendor/bin/php-cs-fixer fix --dry-run
      - run:
        command: |
          mkdir -p ~/phpunit
          ./bin/phpunit --log-junit ~/phpunit/junit.xml tests
        when: always

      - store_test_results:
          path: ~/phpunit

      - store_artifacts:
          path: ~/phpunit
