index:
    path: /
    controller: App\Controller\DefaultController::index

arriving:
    path: /arriving
    controller: App\Controller\DefaultController::arriving

leaving:
    path: /leaving
    controller: App\Controller\DefaultController::leaving
